### ISSUE TITLE
Sprint Review

### ISSUE THREAD

**Issue by mart1003** [vegan-nutrition/project-v#17]
In this sprint, we focused on research for the UX portion of the site. We conducted competitive analysis, created personas and collected data via a survey. We also started coming up with the logo.

@thomasjbradley

**Comment by mart1003** [comment]
The sprint was successful, as we completed the tasks we set out to do. 
I feel that we could hav tried to communicate more outside of class time.

**Comment by bryanchanchan** [comment]
The sprint was successful for this week, finished all the tasks that was assigned last week. Things to improve on are communicating through slack more so we know if anyone of us is struggling on certain task.

**Comment by EvyCat** [comment]
The sprint this week was a success. All tasks finished on time. I was unable to make it to class this week but otherwise things went well. I agree on the communication, even if there is no issues just keeping each other updated would be ideal.

**Comment by thomasjbradley** [comment]
👍
